version: "3.9"
services:
  swaggerui:
    container_name: appwrite-swagger-ui
    build:
        context: .
    ports:
      - 8080:8080
    environment:
      URL: https://appwrite.io/specs/swagger2?platform=server